version: '3.7'


services:
  motorcyclerental.rabbitmq-compose:
    image: rabbitmq:3.13-management
    networks:
      - elastic
    container_name: motorcyclerental.rabbitmq-compose
    ports:
     - "5672:5672"
     - "15672:15672"


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    networks:
      - elastic
    container_name: motorcyclerental.elasticsearch
    ports:
     - 9200:9200
    volumes:
     - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
    - xpack.security.enabled=false
    - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    networks:
      - elastic
    container_name: motorcyclerental.kibana
    ports:
     - 5601:5601
    depends_on:
    - elasticsearch
    environment:
     - ELASTICSEARCH_URL=http://localhost:9200

volumes:
   elasticsearch-data:

networks:
   elastic:
    driver: bridge